models:
  - path: "./assets/X/X.fbx"
    position: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 0.1, y: 0.1, z: 0.1 }
  - path: "./assets/X/X.fbx"
    position: { x: 10.0, y: 0.0, z: 0.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 0.1, y: 0.1, z: 0.1 }
  - path: "./assets/cube/cube.obj"
    position: { x: 4.0, y: 5.0, z: 0.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }
