models:
  - path: "./assets/cube/cube.obj"
    position: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }
  - path: "./assets/cube/cube.obj"
    position: { x: 10.0, y: 0.0, z: 5.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }
  - path: "./assets/cube/cube.obj"
    position: { x: -10.0, y: 0.0, z: 5.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }
  - path: "./assets/cube/cube.obj"
    position: { x: 0.0, y: 0.0, z: 10.0 }
    rotation: { x: -90.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }
  - path: "./assets/cube/cube.obj"
    position: { x: 0.0, y: 10.0, z: 3.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }
  - path: "./assets/cube/cube.obj"
    position: { x: 0.0, y: -10.0, z: 3.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0 }
    scale: { x: 1.0, y: 1.0, z: 1.0 }